; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = espidf

build_flags =
    -DBLUEDROID_ENABLED=TRUE
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_BT_BLE_ENABLED=1

; include lib folder!
lib_deps =  lib/BleClient